sudo: false
language: C
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
script:
- sudo apt-get install -y zlib1g-dev p7zip-rar p7zip-full unace unrar zip unzip sharutils rar uudeview mpack arj cabextract file-roller
- pip install wheel
- sh build.sh
deploy:
  provider: packagecloud
  username: capotej
  repository: python-test-package
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "python"
  package_glob: "dist/*.{whl,zip,egg,egg-info,tar,bz2,Z,gz}"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - julio@packagecloud.io
    on_success: change
    on_failure: always
